expressions=("Always have faith. Always have hope."
"The key is to make it."
"Another one."
"Key to more success is clean heart and clean face."
"Smh they get mad when you have joy."
"Baby, you smart. I want you to film me taking a shower."
"You smart! You loyal! You're a genius."
"We go hard. In everything we do we’re going to accomplish our victory and our goal. If it takes a day, a year, or 20 years, we’re going to win. I haven’t taken a loss because everything I’ve done has been a working process to win. From being a kid on them turntables to becoming where I am is not a loss. It’s a blessing."
"Before I went into the studio with Jay Z, Jigga, Hov, I wanted to go to the Marcy Projects in Brooklyn and touch the people and touch the culture."
"Give thanks to the most high."
"They will try to close the door on u, just open it."
"They don’t want you to win. They don’t want you to have the No. 1 record in the country. They don’t want you get healthy. They don’t want you to exercise. And they don’t want you to have that view."
"I don’t have no favorite rock bands. I’m a fan of rock music though."
"I wanted to see what type of trees is growing in Marcy Projects, what type of water Jay Z was drinking."
"Those that weather the storm r the great ones."
"The key to more success is coco butter."
"I changed… a lot."
"My fans expect me to be greater and keep being great."
"They don’t want you to jet ski."
"Congratulations, you played yourself."
"You want my advice? Don’t play yourself."
"Another one, no. Another two, drop two singles at a time."
"They kick you when you’re down, but they wanna kick it when you’re up."
"You can never run out of keys."
"You gotta water your plants. Nobody can water them for you."
"Stay focused and secure your bag, because they want you to fail and they don’t want us to win."
"I’m all about peace. I’m all about unity. I’m all about love."
"We gonna win more. We gonna live more. We the best."
"I’m gonna go hard no matter what because I gotta feed my family and I gotta feed myself."
"The key is that I’m the king."
"To succeed, you must believe. When you believe, you will succeed."
"Bless up. Don’t play yourself"
"You do know it cost money to put a t-shirt on your back? You do know it cost money have a house? You do know it cost money to eat? Get money, don’t let these people fool you."
"We have to get money. We have no choice. It cost money to eat."
"They never said winning was easy."
"The key is: never fold"
"There will be roadblocks but we will overcome them."
"When you stop making excuses and you work hard and go hard you will be very successful."
"Almond milk + cinnamon crunch = major key to success"
"Watch your back, but more importantly when you get out the shower, dry your back. It’s a cold world out there."
"I remember when I ain’t have a jacuzzi"
"The other day the grass was brown, now its green cuz I ain’t give up. Never surrender."
"I can deal with everything. I got the answer for anything. This DJ Khaled.")
selectedexpression=${expressions[$RANDOM % ${#expressions[@]} ]}


